var words = {
  "me preocupo": "(I) worry, I'm worried",
  encuentra: "find, finds, encounters",
  vi: "saw, see, (I) saw",
  viste: "saw, (?) did you see, (?) did you watch",
  comprender: "understand, (to) understand, realize",
  cogí: "caught, made, (I) took",
  parar: "to stop, (to) stop, (to) stay",
  empecé: "(I) started, (I) began, started",
  responder: "to answer, (to) respond to, (to) respond",
  empezó: "(he) began, (?) did it start, (she) started",
  ejemplo: "instance, example, lead",
  necesitar: "to need, (to) need",
  "nos sentamos": "(we) sit, (?) should we sit, (we) sat down",
  sentarnos: "(to) sit, sit, be seated",
  enseñando: "teaching",
  preocuparse: "to worry",
  habló: "speak, (?) did he talk, (he) spoke",
  estudió: "studied, study, (he) studied",
  seiscientos: "six hundred, 600",
  caminaron: "(?) did you walk, (they) walked, walk",
  disfrutando: "enjoying",
  compraron: "fixed, (?) did you buy, buy",
  encontraron: "(they) found, found, (?) did you find",
  ruido: "noise, noisy, sound",
  posible: "possible",
  quinientos: "five hundred",
  entonces: "then, so, anyway",
  vinimos: "(we) arrived, (we) came, come",
  compraste: "(?) did you buy, (?) did you get, (you) bought",
  vinieron: "(they) came, (?) did you come, come",
  encontramos: "(we) find, (we) found, found",
  siguiente: "following, next",
  fumar: "to smoke",
  querría: "(I) would like, (he) would want, want",
  "algo de": "some",
  cuatrocientos: "four hundred",
  alguien: "anyone, someone, somebody",
  "nos vemos": "see you",
  espere: "hold on, (you) wait, wait",
  viniste: "(you) came, (?) did you come, come",
  trescientos: "three hundred",
  vine: "(I) arrived, (I) came, come",
  nacionalidad: "nationality",
  llovió: "(it) rained, rain",
  montaste: "(?) did you ride, start, (you) rode",
  nevó: "(it) snowed, snow",
  "nos encontramos": "we met up, (we) are meeting up, (?) are we meeting up",
  corrió: "run, (she) ran, (you) ran",
  haber: "had, (to) be, (to) have",
  caminó: "(he) walked, (?) did you walk, (she) walked",
  lluvia: "rain, barrage, hail",
  comienzo: "(I) begin, beginning, (I) start",
  árbol: "tree",
  duermo: "I am sleeping, sleep, (I) fall asleep",
  "me encuentro": "feel, (I) meet up, i'm",
  encantar: "to love",
  nevando: "snowing",
  comenzamos: "(we) started, (we) began, (?) do we start",
  lloviendo: "raining",
  encontrarme: "(to) meet up, meeting up",
  comenzar: "to start, (to) commence, (to) begin",
  nevar: "to snow",
  llover: "to rain, (to) leak",
  clima: "weather, climate",
  caluroso: "hot, warm",
  usando: "using, wearing, (?) are you using",
  encontró: "(he) found, encountered, (she) found",
  emocionante: "exciting, moving",
  oración: "sentence, prayer",
  duro: "heavier, tight, severe",
  gracioso: "funny",
  elegimos: "(we) are choosing, choose, (we) choose",
  pagaste: "pay, (you) paid for, (?) did you pay for",
  elijo: "(?) should I choose, (I) choose, I'm choosing",
  querer: "to want, love, like",
  eliges: "(you) choose, (?) can you choose, choose",
  anuncio: "advertisement, sign, announcement",
  encontraste: "(you) found, (?) did you find, find",
  "el mío": "mine",
  ahí: "there, then",
  coge: "makes, (he) takes, takes",
  vida: "lifetime, life, lives",
  coger: "to take",
  "el azul": "the blue one",
  cojo: "get, taking, (I) take",
  encontré: "find, found, met up",
  "el rojo": "the red one",
  "la amarilla": "the yellow one",
  algún: "any, a, one",
  pagamos: "pay, paid, are paying for",
  doscientos: "two hundred",
  gran: "great, big, large",
  tercer: "third",
  ningún: "any, none, no",
  olvidar: "to forget, (to) leave … behind",
  pagó: "(he) paid for, (?) did you pay, pay",
  buen: "good, nice, great",
  primer: "first",
  tercero: "third",
  segundo: "second, 2",
  completamente: "completely",
  ay: "oh, ouch",
  último: "past, final, last",
  ninguno: "neither, none of them, any",
  pobre: "poor, poor thing",
  elegir: "choose, select",
  nadie: "nobody, no one, no-one",
  ciento: "a hundred, percent, one hundred",
  compró: "fixed, (?) did she buy, (she) got",
  compré: "(I) bought, buy, get",
  escribiste: "(?) did you write, write, (you) wrote",
  hizo: "(he) made, made, asked",
  escribí: "(I) wrote, write, (I) typed",
  conoció: "know, (he) met, (?) did they meet",
  bebieron: "drink, (they) drank, (?) did you drink",
  hicieron: "(they) took, work, (they) went",
  cogimos: "made, (we) took, get",
  disfrutaron: "(?) did you enjoy, enjoy, (you) enjoyed",
  caminé: "(I) walked, walk",
  disfrutaste: "(?) did you enjoy, enjoyed, enjoy",
  hice: "(I) asked, (I) did, (I) took",
  visitó: "(she) visited, (?) did you visit, visit",
  hicimos: "work, made, packed",
  hiciste: "(?) did you play, become, made",
  saliste: "(?) did you go out, (you) went out, (?) did you leave",
  abriste: "(?) did you open, start, bored",
  salí: "left, (I) left, appeared",
  abrí: "open, get, got",
  conocieron: "(?) did you meet, (they) met, meet",
  bebió: "drink, (?) did you drink, (she) had",
  disfrutó: "(it) enjoyed, (he) enjoyed, (she) enjoyed",
  disfruté: "(I) enjoy, (I) enjoyed, enjoy",
  viajó: "travel, (she) traveled, (he) traveled",
  caminaste: "walk, (you) walked, (?) did you walk",
  viajaron: "travel, (they) traveled, (?) did you travel",
  miramos: "look, watch, (we) looked at",
  visitaron: "(they) visited, visit, (?) did you visit",
  estuvimos: "we were, (we) stayed, is",
  aprendimos: "learn, (we) learned, learned",
  conocimos: "(we) knew, (we) met, meet",
  barco: "ship, boat, riverboat",
  escuchamos: "(we) are are listening to, heard, (we) listened to",
  visitamos: "(we) visit, (we) visited, visit",
  montamos: "(we) ride, start, (we) rode",
  cenamos: "(we) have dinner, (we) had dinner, (we) ate dinner",
  bailamos: "(we) dance, (we) danced, (?) should we dance",
  fuimos: "go, (we) were, (we) went",
  querido: "dear, wanted",
  anoche: "last night",
  corrimos: "(we) ran, run, (we) went running",
  comimos: "ate, (we) had, (we) ate",
  vimos: "saw, see, (we) saw",
  dormimos: "(we) sleep, (we) slept, (we) fell asleep",
  bebimos: "(we) drank, drank",
  nadamos: "(we) swam, (we) swim, swim",
  pasamos: "we're stopping by, passed, (?) did we send",
  disfrutamos: "(we) enjoyed, (we) enjoy, (we) are enjoying",
  caminamos: "(we) are walking, (we) walk, (we) walked",
  viajamos: "traveled, (we) are traveling, (we) traveled",
  practicamos: "played, practice",
  nieve: "snow",
  salieron: "(they) went out, go, leave",
  salió: "(she) went out, (he) left, out",
  comieron: "(they) ate, eat, (?) did you eat",
  comió: "(?) did she eat, ate, (he) ate",
  estuvieron: "they were, (they/you-plural) were, (they/you-plural) stayed",
  estuvo: "it was, (he/she/it/you) stayed, (you-formal) were",
  pez: "fish",
  cocinó: "cook, (she) cooked, (he) cooked",
  lavó: "wash, (he) washed, washed",
  fueron: "(they) went, go, (?) did they go",
  lavaron: "(?) did they wash, wash, (they) washed",
  fue: "was, (he) went, (?) did he go",
  cocinaron: "cook, (?) did they cook, (they) cooked",
  búho: "owl",
  abrieron: "open, (?) did they open, (they) opened",
  escribieron: "(?) did they write, write, (they) wrote",
  aprendió: "(she) learned, learn, (he) learned",
  abrió: "(?) did she open, open, start",
  escribió: "(?) did you write, (she) wrote, (he) wrote",
  aprendieron: "(?) did you learn, learn, (they) learned",
  cerdo: "pig, pork",
  limpiaron: "clean, (they) cleaned, (?) did they clean",
  miraron: "(they) watched, (?) did they watch, (they) looked",
  limpió: "(she) cleaned, clean",
  miró: "look, (he) watched, (he) looked at",
  cerraron: "(?) did they close, (they) closed, close",
  cerró: "(she) shut, (he) closed, (?) did he shut",
  vaca: "cow",
  aprendiste: "(?) did you learn, learn, (you) learned",
  conocí: "know, knew, (I) knew",
  estuviste: "you were, (you) stayed, are",
  conociste: "know, (you) met, (?) did you meet",
  aprendí: "(I) learned, learned",
  estuve: "I was, (I) stayed",
  "hace mucho tiempo": "a long time ago",
  estudiaste: "(you) studied, (?) did you study, studied",
  estudié: "study, (I) studied, studied",
  visité: "(I) visited, visited",
  visitaste: "visit, (?) did you visit, (you) visited",
  fui: "(I) left, go, went",
  fuiste: "is, left, go",
  viaje: "trip, travel, drive",
  viví: "(I) lived, lived",
  comiste: "eat, (?) did you eat, (you) ate",
  viviste: "(?) did you live, (you) lived, lived",
  comí: "(I) had, (I) ate, had",
  bebiste: "drink, (you) drank, (?) did you drink",
  ayer: "yesterday, past",
  bebí: "(I) had, drink, (I) drank",
  viajaste: "(you) traveled, travel, (?) did you travel",
  viajé: "travel, (I) traveled, traveled",
  hablaste: "said, (?) did you speak, (you) said",
  hablé: "speak, spoke, talk",
  probaste: "try, touch, (?) did you try",
  probé: "try, taste, (I) tried",
  pasado: "last, had, passed",
  dentro: "inside, in, within",
  fuera: "outside",
  final: "end, final, ending",
  abajo: "downstairs, down, to go to pieces",
  atrás: "ago, in the back, at the back",
  arriba: "upstairs, come on!, above",
  espero: "(I) am waiting for, (I) wait, (I) hope",
  detrás: "behind",
  entre: "between, among, (I/he/she/it/you) enter",
  buscando: "looking for, searching for, wanting",
  seguir: "to continue, to keep, to follow",
  direcciones: "directions, headship, managements",
  carretera: "highway, road",
  giro: "(?) do I turn, (I) turn, turn",
  enfrente:
    "in front, (I/he/she/it/you) bring … face to face, (I/he/she/it/you) bring … into conflict",
  disculpa: "excuse me, apology",
  gira: "(it) turns, (you) turn, turn",
  sigue: "(you) go, is following, keeps",
  perdona: "pardon me, forgive me, excuse me",
  derecho: "straight",
  gire: "take, (you) take, (you) turn",
  girar: "to turn",
  perdone: "pardon me, excuse me, forgive",
  tome: "drink, go, take",
  siga: "follow, (you) continue, continue",
  cercano: "close, nearby, closed",
  nada: "nothing, (he/she/it) swims, (you-formal) swim",
  decimos: "(we) tell, (?) do we say, (we) say",
  preguntar: "to ask, (to) wonder",
  millón: "million, millionth",
  portuguesa: "Portuguese",
  pregunto: "(I) wonder, (I) ask, ask",
  mil: "one thousand, (number) one thousand",
  almuerza: "(he) eats lunch, (you) eat lunch, (she) eats lunch",
  dices: "(?) can you tell, you're saying, (?) could you tell",
  mando: "(I) send, should I send, direct",
  mesero: "waiter, server",
  digo: "speak, (I) say, go",
  les: "hers, they, him",
  mandar: "to send",
  oficinas: "offices",
  noventa: "ninety",
  cien: "one hundred, a/one hundred",
  das: "(?) could you give me, (?) are you giving, (you) give",
  setenta: "seventy",
  "le hago": "I'm asking her, (I) ask her, I'm asking him",
  doy: "giving, I'm giving, should I give",
  dar: "to give, (to) give on to, (to) lead to",
  ochenta: "eighty, number eighty",
  le: "her, to her, they",
  hermoso: "beautiful, lovely, beautifully",
  allá: "there, over there",
  lávese: "(you) wash, wash",
  lávate: "wash, (you) wash, (you) wash yourself",
  siéntate: "(you) sit, (you) sit down",
  siéntese: "(you) sit down",
  acá: "here, Acá",
  miro: "(I) look at, watching, (I) am watching",
  levántese: "(you) get up",
  levántate: "(you) get up",
  sentarse: "(to) sit down, (to) sit, sit",
  cuartos: "bedrooms, rooms, fourth (num.)",
  ducha: "shower",
  traigo: "get, (?) should I bring, (I) bring",
  granja: "farm",
  piso: "ground, floor, press",
  pared: "wall",
  césped: "grass, lawn",
  seguro: "insurance, positive, surely",
  coges: "get, taking, (you) take",
  "nos ayudas": "(?) can you help us",
  eso: "that",
  traes: "(you) bring, (?) can you bring",
  caja: "box, checkout",
  ponerme: "(to) wear, putting on, put",
  quedarme: "stay, (to) stay, (to) fall",
  quedarnos: "(to) stay, staying, stay",
  probarte: "(to) try on, trying on",
  ponerte: "(to) put on, putting on, put",
  esperar: "to wait, (to) wait for, (to) hope",
  aldea: "village, town, villages",
  levantarme: "(to) get up, wake up, getting up",
  probarse: "to try on",
  levantarte: "(you) get up",
  ducharte: "(to) shower, shower",
  lavarnos: "(to) wash, wash",
  pie: "foot, stood, based",
  oreja: "ear",
  encontrar: "to find, (to) find, (to) meet",
  desayunar: "to have breakfast",
  recordar: "to remember, (to) remind, (to) recall",
  papel: "role, paper, part",
  entrada: "ticket, driven, starter",
  librería: "bookstore, bookshop",
  volar: "to fly",
  cenar: "dinner, (to) eat dinner, (to) have dinner",
  luego: "later, then, later on",
  pensar: "to think, (to) think about, (to) expect",
  venimos: "(we) are coming, (we) come, (we) arrive",
  pensando: "thinking, planning, think",
  piensa: "do you plan, (he) plans, (he) thinks",
  pensamos: "(we) thought, (we) think, (we) are thinking",
  "por supuesto": "of course",
  pienso: "think, planning, figured",
  decir: "to say, (to) say to oneself, tell",
  gustar: "to like",
  invitar: "to invite, have",
  viene: "(?) does she come, (he) comes, come",
  "se queda": "falls, (he) is staying, remains",
  cambiar: "(to) change, replace, change",
  venir: "to come, come, (to) arrive",
  vengo: "I'm coming, (I) come, come",
  gustaría: "like, (?) would you like",
  "todo el mundo": "everybody",
  "me quedo": "(I) stay, I'm staying",
  vuelvo: "(I) return, (I) go back, return",
  puedes: "can, (you) may, (?) could you",
  "que viene": "next",
  empiezas: "(you) begin, open, (you) start",
  primero: "first",
  quedarse: "to stay, (to) stay (oneself), (to) keep (oneself)",
  fecha: "date",
  plan: "planned, plan, designed",
  "todo el tiempo": "all the time",
  gatos: "cats, noughts and crosses, amateurs",
  cafés: "cafés, coffees, brown",
  imagen: "image, picture",
  salsa: "sauce, salsa, dip",
  ligero: "lit, mild, light",
  todos: "all, all of, everybody",
  "los necesita": "(she) needs them, (he) needs them",
  abro: "I'm opening, drive, open",
  cierro: "close, (I) close, (?) should I close",
  malo: "mean, bad, wrong",
  lento: "slow, slowly",
  paquete: "package, pack",
  ya: "already, now, right now",
  "la quiero": "(I) want it",
  "las comen": "(they) eat them",
  pruebas: "try, touch, (you) try",
  bici: "bike",
  "lo quiero": "(I) want it",
  bebemos: "(we) drink, we're having, drink",
  lo: "they, him, you",
  tés: "teas",
  "lo compro": "I'm buying it",
  dibujando: "drawing",
  bebiendo: "drinking, he's having, having",
  leyendo: "reading",
  escuelas: "schools, coaching, colleges",
  saliendo: "coming out, leading, leave",
  abriendo: "opening",
  escribiendo: "writing",
  pizarra: "chalkboard, blackboard, whiteboard",
  nota: "note, grade, (he) notices",
  aprendiendo: "learning",
  haciendo: "doing, acting, getting",
  comiendo: "eating, having, taking",
  diccionario: "dictionary",
  hablando: "talking, speaking, ringing",
  estudiando: "studying",
  escuchando: "listening to, hearing, listening",
  lección: "lesson, lecture",
  aula: "classroom",
  "se cepillan": "(they) brush, (you) brush",
  "nos cepillamos": "(we) are brushing, (we) brush",
  cepillarse: "to brush",
  "cepillo de dientes": "toothbrush",
  cepillo: "brush, hair, hairbrush",
  diente: "tooth, teeth",
  "me cepillo": "(I) brush",
  "se sienten": "(?) do you feel, (they) feel, feel",
  "nos sentimos": "feel",
  "se ponen": "(you) put on, put, (you) are putting on",
  "nos ponemos": "makes us, (we) put on, put",
  tuyo: "yours",
  suyo: "hers, yours, theirs",
  "se levantan": "(they) get up, (?) do you get up, stands up",
  "se duchan": "(?) are they showering, (they) shower, (?) do you shower",
  "se lavan": "(you) wash, (they) wash themselves",
  llave: "key, lock",
  cara: "face, expensive, faces",
  cabello: "hair",
  mío: "mine",
  "nos duchamos": "we shower, (we) are showering, (we) showered",
  lavarse: "to wash, to wash up, to wash yourself up",
  "nos llamamos": "our names are",
  "nos levantamos": "(we) get up, (?) are we getting up, (we) got up",
  "me lavo": "(I) wash",
  mano: "hand",
  beba: "drink, (you) drink, have",
  vuelva: "get back, (you) come back, (he/she) returns",
  escriba: "(you) write, writes, write",
  lápiz: "pencil",
  vuelve: "(you) come back, (you) return, (?) are you coming back",
  abres: "unlocking, open, (?) can you open",
  página: "page",
  hable: "speaks, (you) speak, talk",
  trabaje: "(you) work, work, works",
  pruebe: "tries, (you) try, try",
  despacio: "slowly, gently, quietly",
  pongo: "(?) should I put, (I) get, (I) put",
  poner: "to put, (to) put on, (to) put in",
  pones: "(you) play, (you) put, play",
  lavar: "(to) wash, washed, wash",
  refrigerador: "fridge, refrigerator, refrigerators",
  cincuenta: "fifty, number fifty",
  cuarenta: "forty, number forty",
  llevar: "to carry, (to) wear, (to) ride",
  sesenta: "sixty",
  centavo: "cent, penny",
  chorizo: "sausage, chorizo",
  picante: "hot, spicy, salty",
  mantequilla: "butter",
  "tienen que": "has to, need, (they) have to",
  cuánta: "how much",
  vegetal: "vegetable, plant",
  papa: "potato",
  huevo: "egg, ball, lump",
  compra: "(he) is buying, groceries, buy",
  "tenemos que": "(?) do we need to, (we) have to, need",
  plátano: "banana",
  bolsa: "bag",
  fruta: "fruit",
  kilo: "kilo, kilogram",
  vaqueros: "jeans",
  lentes: "glasses, spectacles, lenses",
  ambos: "both",
  par: "pair, couple",
  color: "color, colors, dye",
  bota: "boot, jump",
  bailes: "dances",
  interesan: "interest, (we) are interested",
  pájaro: "bird",
  sitio: "site, location, place",
  rápido: "quick, quickly, smarter",
  tipo: "types, kinds, stick",
  flor: "flower",
  francesa: "French",
  ojo: "eye, look out",
  caliente: "hot, warm",
  encantan: "(we) love, (I) love",
  bananas: "bananas",
  gustan: "(?) do they like, (we) like, (I) like",
  vinos: "wines, receptions",
  ensaladas: "salads",
  chileno: "Chilean",
  dulce: "mild, softer, milder",
  veintinueve: "twenty-nine",
  veintiocho: "twenty-eight",
  treinta: "thirty, (number) thirty",
  cuarto: "quarter, room, bedroom",
  cámara: "camera",
  minuto: "minute",
  por: "to, because, through",
  pronto: "soon, early, prompt",
  veintiséis: "twenty-six",
  veintisiete: "twenty-seven",
  estar: "being, (to) be, were",
  taxis: "taxis",
  carros: "cars, automobiles, carriages",
  adónde: "where",
  "van a": "will",
  "vamos a": "will",
  llegar: "to arrive, (to) reach, (to) come",
  listo: "smart, ready, cute",
  avión: "plane, airplane, aircraft",
  boletos: "tickets, coupons",
  "vas a": "you're, attend, will",
  maletas: "suitcases, Luggage, bags",
  "va a": "is, she's, will",
  pasaportes: "passports",
  "voy a": "will, i'm",
  próximo: "next, nearest, ahead",
  popular: "popular, folk",
  "la más": "the most",
  "el peor": "the worst one",
  "el más": "the most",
  mundo: "world",
  gordo: "fat",
  delgado: "thin, slim, slight",
  tan: "that, so, as",
  famoso: "celebrated, famous, celebrity",
  peor: "worse, worst",
  mejor: "the better, better, best",
  bello: "beautiful, pretty",
  que: "than, that, to",
  menos: "minus, fewer, but",
  cómodo: "idle, comfy, convenient",
  blusa: "blouse",
  gorra: "cap",
  japonés: "Japanese",
  lengua: "language, tongues, tongue",
  mismo: "same, himself",
  chino: "Chinese, curly",
  cantar: "(to) sing, singing, sing",
  canción: "song",
  "sabes nadar": "(you) know how to swim",
  carnes: "meats",
  cocinar: "(to) cook, how to cook, cooking",
  manejar: "drive, driving, handles",
  "cómo se escribe": "(?) how do you write",
  "no lo sé": "I do not know, I don't know",
  "sabes cuándo": "(?) do you know when",
  "sabes quién": "(?) do you know who",
  "sabe usted": "(?) do you know",
  "cómo se dice": "(?) how do you say",
  saber: "to know, (to) know, (to) know how to swim",
  sé: "know, can, (I) know how to",
  sabes: "(you) know, know, (?) do you know",
  edad: "age",
  palabra: "word",
  respuesta: "answer, response, reply",
  esto: "this",
  partidos: "games, matches, administrative area",
  fiestas: "parties, festival, festivals",
  radio: "radio",
  asignatura: "subject",
  grupo: "band, group, stood",
  practicar: "to practice",
  básquetbol: "basketball",
  jugamos: "(we) are playing, (we) play, played",
  cuáles: "which, what, which ones",
  juego: "playing, games, play",
  preferir: "preferring, preferred, (to) prefer",
  importantes: "important, considerable (plural), serious (plural)",
  pintura: "painting, paint",
  arte: "art",
  europeo: "European",
  "me interesa": "I'm interested in, (it) interests me, I am interested in",
  "le interesa": "(he) is interested in, (she) is interested in, is into",
  "les interesa": "(?) are you interested in, (they) are interested in",
  "te interesa": "(?) does it interest you, (?) are you interested in",
  "nos interesa": "(we) are interested in",
  conversación: "conversation",
  foto: "picture, photo, photos",
  agosto: "August, (I) wither, (I) parch",
  septiembre: "September",
  diciembre: "December",
  octubre: "October",
  noviembre: "November",
  mes: "month",
  otoño: "autumn, fall",
  nieva: "snow, (it) snows, (?) is it snowing",
  abril: "April",
  llueve: "(?) does it rain, (it) rains, raining",
  junio: "June",
  julio: "July, joule",
  mayo: "May",
  primavera: "spring, springtime",
  marzo: "March",
  febrero: "February",
  "cómo está el tiempo": "how's the weather",
  enero: "January",
  nublado: "cloudy",
  oscuro: "dark, darker",
  invierno: "winter",
  sol: "sun, G, so",
  "qué tiempo hace": "what's the weather like",
  viento: "wind, windy",
  pierdes: "(you) miss, lose, (you) are wasting",
  entendemos: "(we) understand, understand",
  pierden: "(they) lose, (they) are losing, lose",
  entender: "to understand",
  entiende: "understand, (?) do you understand, (he) understands",
  perder: "to lose, (to) miss, (to) lose one's way",
  entienden: "(?) do you understand, understand, (they) understand",
  perdemos: "lose, (we) lose, (we) miss",
  entiendo: "(I) can understand, understand, get",
  empezar: "to start, (to) begin, (to) open",
  cerramos: "(we) closed, (we) close, (we) lock",
  cierran: "(they) close, (you) are closing, close",
  empieza: "begin, (?) does it start, (it) begins",
  empiezan: "(they) are starting, (they) start, start",
  empiezo: "(I) am starting, (I) start, start",
  cerrar: "to close, (to) close up, (to) close down",
  empezamos: "(we) started, begin, (we) start",
  cierras: "(?) do you close, (?) can you close, (you) are closing",
  volver: "to go back, to return, come back",
  puedo: "(I) can, can, may I",
  pueden: "(they) can, (you) could, may",
  podemos: "can, (?) can we, (we) can",
  vuelven: "again, (they) are going back, (you) go back",
  vuelves: "(you) come back, (you) are going back, (you) return",
  puede: "(I) may, (?) could you, (?) can you",
  poder: "to be able to",
  volvemos: "(we) are going back, (we) return, (we) go",
  almuerzas: "(?) are you having lunch, (?) do you have lunch, lunch",
  almorzamos: "(we) eat lunch, (we) have lunch, (we) are having lunch",
  prueban: "try, touch, (they) try",
  pruebo: "try, touch, essay",
  probamos: "(we) try, (we) are trying, try",
  prueba: "try, touch, quiz",
  almorzar: "to have lunch, (to) have elevenses, (to) have a mid-morning snack",
  almuerzan: "(they) eat lunch, (they) are having lunch, (you) have lunch",
  probar: "to try, (to) try on, (to) prove",
  salgo: "(I) leave, I'm leaving, leaving",
  temprano: "early",
  semanas: "weeks, allowances, pocket money",
  sale: "departs, issues, (he) is leaving",
  levantarse: "to get up, (to) take (oneself), (to) pinch (oneself)",
  "te pones": "(you) put on, (you) wear, (?) are you putting on",
  "me pongo": "(I) am putting on, I'm putting on, (I) put on",
  cada: "every, each",
  "se pone": "(he) puts on, (she) puts on, (?) is she putting on",
  ponerse: "to put on, (to) take (oneself), (to) fit (oneself)",
  ducharse: "(to) shower, (to) take a shower, shower",
  antes: "before, previously, first",
  después: "after, next, afterward",
  solo: "by itself, by myself, by yourself",
  cosa: "thing",
  diario: "paper, daily, newspaper",
  tomo: "(I) drink, drink, (I) am taking",
  hago: "made, (I) make, make",
  hacer: "to do, (to) do, (to) make",
  cena: "dinner, supper",
  tarea: "homework, assignment, task",
  desayuno: "breakfast, (I) eat breakfast",
  haces: "(you) make, (?) are you doing, made",
  almuerzo: "lunch, (I) eat lunch",
  "me ayudas": "(you) help me, (?) can you help me, (?) will you help me",
  "nos ayudan": "(they) help us",
  "me enseña": "(she) is teaching me, (he) teaches me, (he) is teaching me",
  idioma: "language",
  alemán: "German",
  curso: "course, class, grade",
  "te necesito": "(I) need you",
  "nos llamas": "call us",
  "me ama": "(she) loves me",
  "me llaman": "(they) call me",
  "nos escuchan": "(they) listen to us",
  "te llamamos": "(we) call you",
  "nos visita": "(she) is visiting us, (he) visits us, (he) is visiting us",
  "te conozco": "(I) know you",
  "nos conocen": "(they) know us, they've known us",
  "me necesita": "(she) needs me, (he) needs me",
  "me conoce": "(he) knows me, (you) know me, (she) knows me",
  "te visitan": "(they) visit you",
  "me escucha": "(he) listens to me, (she) listens to me, (you) listen to me",
  "te compra": "(she) buys you, (he) buys you",
  "nos compra": "(he) buys us, (she) buys us",
  "me compra": "(she) buys me, (he) is buying me, (he) buys me",
  te: "your, you, yourself",
  nos: "we, for us, ourselves",
  me: "myself, I, me",
  muñeca: "doll, wrist",
  ganas: "(you) win, (you) earn, make",
  "de verdad": "real, for real, really",
  miedo: "scared, fear, afraid",
  sueño: "tired, dream, sleepy",
  bailar: "(to) dance, how to dance, dancing",
  animal: "animal",
  calor: "hot, warm, heat",
  puesto: "(I) have on, put, on",
  frío: "cold, (I) fry, (I) waste",
  largo: "long",
  veinticuatro: "twenty-four",
  veintitrés: "twenty-three",
  jugos: "juices",
  hambre: "hunger, hungry",
  veinticinco: "twenty-five",
  sed: "thirsty, thirst",
  pizza: "pizza",
  veintiuno: "twenty-one, twenty first",
  veintidós: "twenty-two",
  señoritas: "ladies, girls, young ladies",
  jóvenes: "young, young people, young women",
  veintiún: "twenty-one",
  "cuántos años": "how old",
  adulto: "adult",
  tele: "TV, television, telly",
  enseñar: "(to) teach, teach, taught",
  amar: "(to) love, love",
  ver: "saw, (to) look, watching",
  usualmente: "usually, normally",
  llamar: "calling, hails, telephone",
  ayudar: "help, assist, helping",
  alguno: "any, some (people), one",
  pueblos: "towns, peoples, small town",
  gente: "people, good, kind",
  lugar: "location, place, stood",
  parte: "part, leaves, some",
  visitar: "(to) visit, visiting, visit",
  conozco: "know, I'm familiar with, (I) know",
  conocer: "to meet, know, (to) know",
  país: "country, land",
  conoces: "(you) know, (?) are you familiar with, (?) have you known",
  río: "Rio, (I) am laughing, river",
  pelota: "ball",
  caballo: "horse, horses",
  montar: "riding, (to) ride, ride",
  normalmente: "normally, usually",
  "a nosotros": "us",
  tiempo: "time, to play for time, weather",
  pasar: "passing, go, spending",
  "a él": "he",
  tenis: "tennis, plimsoll, running shoe",
  "a ti": "you",
  "a mí": "i, me",
  zoológico: "zoo",
  "para él": "in his opinion",
  "les gusta": "(?) do they like, (they) like, like",
  "para ella": "in her opinion",
  "les encanta": "(?) do they love, (they) love, loves",
  aquel: "that",
  inteligentes: "intelligent, smart",
  persona: "person",
  estudioso: "studious",
  perezoso: "lazy",
  responsable: "responsible, reliable",
  rubio: "blond",
  moreno: "darker, dark-haired, brunette",
  amarillo: "yellow",
  guapo: "good-looking, handsome, dressed-up",
  negro: "black",
  sucio: "dirty",
  abierto: "driven, made, open",
  limpio: "wash, clearer, I am cleaning",
  felices: "happy",
  tristes: "sad",
  nervioso: "nervous, tense",
  emocionados: "excited",
  diecisiete: "seventeen, number seventeen",
  dieciséis: "sixteen",
  veinte: "twenty, (number) twenty",
  "en efectivo": "with cash",
  diecinueve: "nineteen, number nineteen",
  dieciocho: "eighteen, number eighteen",
  "tarjeta de crédito": "credit card, credit",
  cuesta: "is, it's hard, (it) is",
  cuestan: "(they) cost, (?) do they cost, are",
  trece: "thirteen, (number) thirteen",
  quince: "fifteen, (number) fifteen",
  catorce: "fourteen",
  dólar: "dollar",
  peso: "(I) weigh out, shot, weight",
  "me puedo probar": "(?) can I try on",
  precio: "price, charge, deal",
  talla: "size, carve",
  probador: "fitting room",
  buscar: "to look for, (to) look for, (to) look up",
  ti: "you, yourself",
  cierra: "(you) close, (?) does it close, lock",
  "de compras": "shopping",
  abre: "(it) opens, (?) does it open, open",
  mí: "me",
  películas: "movies, films",
  menor: "little, younger, youngest",
  mayor: "elderly, old, biggest",
  marido: "husband",
  "nos encanta": "we love, love",
  escuchar: "hear, (to) listen, (to) listen to",
  tocar: "to play, to touch, (to) touch",
  "nos gusta": "(we) like, like",
  conciertos: "concerts, concert",
  guitarra: "guitar",
  piano: "piano",
  baloncesto: "basketball",
  "le encanta": "loves, (he) loves, (?) do you love",
  "le gusta": "(he) likes, likes, (?) do you like",
  deporte: "sport, sports",
  "se llaman": "(?) are the names of, their names are, (they) are called",
  padres: "parents, fathers",
  familias: "families",
  nuestro: "our, ours",
  postre: "dessert",
  sopa: "soup",
  frito: "fried, fry",
  patata: "potato",
  blanco: "white",
  botella: "bottle",
  tinto: "red",
  otro: "other, another one, another",
  bebida: "drink",
  "puede traer": "(?) can you bring",
  plato: "dish, course, plate",
  tenedor: "fork",
  cuchillo: "knife",
  cuchara: "spoon",
  quisiera: "(I) would like, (I) wish, wanted",
  frijol: "food, bean",
  menús: "menus",
  cerveza: "beer",
  teléfonos: "phones, telephones",
  celulares: "cell phones",
  debajo: "under",
  jardín: "garden, yard",
  planta: "plants, plant, floor",
  limpiar: "to clean, (to) ice, (to) clear",
  sobre: "on, about, on top of",
  pintar: "to paint, to draw, paint",
  estantería: "bookcase, bookshelf, shelf",
  silla: "chair",
  tenemos: "we're having, (we) are, (?) do we have",
  tienen: "(they) are, (?) is there, make",
  ventana: "window",
  habitación: "room, bedroom",
  hay: "there is, there are, there's",
  cocina: "(he) is cooking, (you) cook, kitchen",
  moderno: "modern, fashionable",
  dormitorio: "room, bedroom, dormitory",
  cama: "bed",
  nevera: "fridge, refrigerator",
  sala: "lounge, living room, room",
  "se levanta": "(he) gets up, (?) does he get up, (?) are you getting up",
  "a qué hora": "when, (?) what time",
  "te duchas": "(?) do you shower, (you) shower, (?) are you showering",
  "te levantas": "(you) get up, (you) are getting up, (?) do you get up",
  doce: "twelve, number twelve",
  once: "eleven, number eleven",
  "se ducha": "(she) showers, (he) showers, showers",
  "me ducho": "(I) shower, shower",
  "me levanto": "(I) get up",
  "tiene que": "(you) have to, (he) needs to, (she) must",
  "tienes que": "(you) need, (you) have to, (you) must",
  "tengo que": "(I) need to, (I) have to, have",
  domingos: "Sundays, Sunday, Sabbath",
  hora: "hour, time",
  vamos: "let's, we're going, (we) are going",
  mirar: "to look, (to) look at, (to) watch",
  van: "(you) go, go, (they) will",
  sábados: "Saturdays, Saturday, Sabbath",
  televisión: "television, TV",
  media: "meant, average, thirty",
  días: "days",
  vas: "(you) go, go, (you) are going",
  "a menudo": "often",
  va: "is, there is going to, (she) goes",
  voy: "go, I will leave, going",
  todo: "all, whole, everybody",
  cine: "theater, movie theater, cinema",
  noche: "night, evening",
  perros: "dogs",
  música: "music, composer, harmonica",
  viejo: "old, old man",
  chico: "boy, small",
  dibujar: "to draw, draw, to sketch",
  nadar: "to swim, swimming, swim",
  "me encanta": "love",
  correr: "to run, run, to race",
  jugar: "to play, (to) play with, (to) game",
  "te encanta": "(?) do you love, love",
  piscina: "pool, swimming pool",
  "te gusta": "(you) like, (?) do you like, you",
  pero: "but, only",
  algo: "something, anything, a little",
  "me gusta": "(I) like, like",
  porque: "because",
  chocolate: "chocolate",
  pastel: "cake",
  salen: "(they) go out, (they) leave, (?) do they leave",
  compramos: "(?) are we buying, (we) bought, (we) buy",
  aprendemos: "(we) learn, learn, (we) are learning",
  salimos: "(we) went out, (we) go out, leave",
  salir: "to leave, to go out, to come out",
  compran: "(they) buy, get, (they) are buying",
  aprenden: "(they) learn, (they) are learning, (?) are you learning",
  abrimos: "(we) open, we, (we) opened",
  abren: "drive, get, (they) are opening",
  beben: "(?) are they drinking, (they) drink, drinks",
  tomamos: "(?) should we have, made, we're drinking",
  trabajamos: "work, (we) worked, (we) work",
  toma: "(she) takes, takes, (he) takes",
  trabajan: "(?) do they work, work, they've worked",
  leen: "(they) read, (you) are reading, (?) do you read",
  viven: "(?) do you live, (they) live, are living",
  abrir: "to open, (to) open out, (to) open up",
  escriben: "(they) are writing, (?) do you write, (they) write",
  verano: "summer, summertime",
  junto: "next, along, together",
  restaurantes: "restaurants",
  arroz: "rice",
  comen: "(?) do you eat, (?) are you eating, (they) eat",
  quieren: "you want, (they/you-plural) love, (they/you-plural) like",
  comida: "eaten, food, meal",
  pollo: "chicken",
  bueno: "well, all right, anyway",
  escribimos: "(we) wrote, write, (we) write",
  casas: "houses, homes, you quash",
  "correos electrónicos": "emails",
  vivimos: "live, (we) lived, (we) have lived",
  tarde: "late, afternoon, evening",
  comemos: "(we) eat, (we) are eating, (?) do you eat",
  sándwiches: "sandwiches",
  caminar: "to walk, walk",
  leemos: "(we) are reading, (we) read, read",
  queremos: "want, (we) want, love",
  periódico: "newspaper, daily newspaper",
  playa: "beach, beaches",
  izquierda: "left",
  tomar: "to take, (to) take in, (to) have",
  derecha: "right, right hand, right-hand",
  metro: "meters, meter, subway",
  "al lado": "next to",
  están: "you are, are, (they/you-plural) are",
  lejos: "far, far away, by far",
  puerta: "door, gate",
  parada: "stops, stop, caught",
  del: "of the, to the",
  al: "to the, with, your",
  estamos: "have been (since), (?) are we, (we) are",
  parque: "park, parks, parked",
  cerca: "close, near, nearby",
  viajar: "to travel, travel",
  ir: "to go, (to) go, (to) go out",
  "cerca de": "close to",
  estación: "station, stations, season",
  mis: "my",
  pequeños: "little, small, young",
  pequeñas: "little, small, tiny",
  necesitan: "(you) need, (they) need, need",
  tus: "your, your (plural)",
  sus: "your, his plural, her plural",
  usan: "(they) use, (they) are wearing, wear",
  estos: "these",
  rojos: "red",
  rojas: "red",
  estas: "these",
  pantalón: "trousers, pants",
  necesitamos: "(?) do we need, (we) need, need",
  bonitos: "beautiful, nice, pretty",
  usamos: "(we) used, (we) wear, (we) use",
  nuevas: "new, newer, newest",
  nuevos: "new, newer, newest",
  bonitas: "nice, pretty, beautiful",
  zapato: "shoe",
  grandes: "big, too big, large",
  interesantes: "interesting",
  verdes: "green, green (plural), 000 peseta note",
  carteras: "purses, wallets, satchels",
  señores: "men, gentlemen, sirs",
  señoras: "ladies, Mrs.",
  cuántas: "how many",
  unas: "some, a few, a",
  vacaciones: "vacation, vacations",
  unos: "some, an, ones",
  cuánto: "how much, what, how long",
  muchas: "many, a lot of, lots of",
  "fines de semana": "weekends",
  ustedes: "you guys, you, you all",
  muchos: "lots of, a lot of, many",
  jugador: "player",
  son: "(?) are they, are, (they) are",
  hablan: "spoken, speaks, speak",
  ellas: "they, them",
  universidades: "universities, colleges",
  ciudades: "cities, towns",
  estudian: "(they) are studying, (they) study, investigate",
  ellos: "they, them",
  hablamos: "(we) speak, (we) are talking, speak",
  nosotras: "we, we (feminine), us",
  estudiamos: "study, (we) study, (we) studied",
  nosotros: "we, us",
  somos: "we are, are, be",
  hombres: "men",
  mujeres: "women, wives",
  "me siento": "I've been feeling (since), I feel, I'm feeling",
  "se siente": "(he) feels, (she) feels, (she) is feeling",
  "te sientes": "(?) do you feel, (?) are you feeling, (you) feel",
  "un poco": "slightly, any, kind of",
  "otra vez": "again",
  bebé: "baby",
  sorprendido: "surprised, shocked",
  nunca: "never",
  "a veces": "sometimes",
  disfrutar: "to enjoy, enjoy",
  dormir: "to sleep, sleep, (to) fall asleep",
  mamá: "mom, mother",
  papá: "dad, father",
  contento: "happier, happy, glad",
  también: "also, too, as well",
  "por qué": "why, reason",
  preocupado: "anxious, worried, concerned",
  aburrido: "boring, bored, uninteresting",
  enojado: "annoyed, mad, angry",
  siempre: "always, providing (that), provided (that)",
  triste: "sad, dismal, gloomy",
  contigo: "with you",
  conmigo: "with me",
  "qué tal": "how's, (?) how are you, how",
  enfermo: "sick, ill",
  emocionar: "move, moves",
  ahora: "now, a moment ago",
  lee: "lees, (she) is reading, read",
  nuevo: "new, newer, newest",
  negocio: "business, store, deal",
  tener: "to have, have",
  "correo electrónico": "email",
  poco: "little, bit, a while",
  cuál: "what, which, which one",
  carta: "letter, card",
  escribe: "(?) does she write, (he) is writing, (you) write",
  escritorio: "desk",
  los: "the, their, your",
  las: "your, the, their",
  mensaje: "message, text",
  secretario: "secretary, minister",
  jefe: "boss, manager",
  inglesa: "English",
  española: "Spanish",
  nueve: "nine",
  diez: "ten",
  año: "year",
  alta: "tall, high",
  simpática: "nice",
  bajo: "short",
  simpático: "nice, sympathetic, pleasant",
  alto: "tall, high, high ground",
  baja: "turns down, goes down, low",
  mascota: "pets, pet, mascot",
  pequeña: "little, tiny, small",
  hijos: "children, sons",
  pequeño: "small , little ones, shorts",
  su: "his, her, your formal",
  bonita: "nice, pretty, beautiful",
  italiano: "Italian",
  seis: "six",
  siete: "seven, number seven, tear",
  estudiantes: "students, university students, college students",
  preguntas: "questions",
  ocho: "eight, number eight",
  clases: "classes, to have classes, classrooms",
  cinco: "five, moment",
  aprendes: "(?) are you learning, (you) learn, learn",
  aprende: "(she) is learning, (he) learns, (she) learns",
  aprender: "to learn, learning, learn",
  aprendo: "(I) am learning, learning, (I) learn",
  esta: "this",
  bibliotecas: "libraries, bookshelves, bookcase",
  cuatro: "four, number four, four-stringed guitar",
  computadoras: "computers",
  biblioteca: "library, bookcase, bookshelves",
  bolígrafos: "pens, ballpoint pens",
  libros: "books",
  cero: "zero, nought, love",
  novio: "boyfriend, fiancé, groom",
  pueblo: "town, people, small town",
  novia: "girlfriend, bride, fiancée",
  médico: "doctor",
  ciudad: "city, town",
  médica: "doctor, medical",
  joven: "young, young man, young woman",
  amiga: "friend",
  ser: "(to) be, be, made",
  dirección: "direction, address, setting",
  amigo: "friend, buddy, bud",
  número: "number, act, constable",
  celular: "cell phone, cellphone, cell",
  portugués: "Portuguese",
  maestra: "teacher",
  camarero: "waiter, barman, bellboy",
  camarera: "waitress, barmaid, maid",
  Francia: "France",
  Inglaterra: "England",
  vivir: "to live, live, (to) be alive",
  vives: "live, (?) do you live, (you) live",
  Europa: "Europe",
  vive: "(he) lives, live, (?) do you live",
  beber: "to drink, drink, drinking",
  vino: "wine, (he/she/it/you) came, (he/she/it/you) arrived",
  comer: "to eat, eat, eating",
  trabajar: "to work",
  trabajo: "work, (I) work, jobs",
  oficina: "office",
  trabaja: "work, (you) are working, (she) is working",
  trabajas: "(?) have you been working, (?) do you work, you've worked",
  fábrica: "factory, stonework",
  quién: "who, who (singular), whom",
  francés: "French",
  hablar: "to speak, to talk, (to) talk about",
  estudia: "(you) study, (she) studies, (?) does he study",
  habla: "(he) is speaking, (?) does he speak, speaks",
  "fin de semana": "weekend",
  disfruta: "(you) enjoy, (he) enjoys, (he) is enjoying",
  película: "movie, film",
  baile: "dance, dance!, dance hall",
  semana: "week, allowance, pocket money",
  favorito: "favorite",
  divertida: "funny, fun",
  fiesta: "party, holiday, don't",
  concierto: "concert, (I) arrange, (I) agree",
  divertido: "fun",
  domingo: "Sunday, Sabbath, allowance",
  sábado: "Saturday, Sabbath",
  viernes: "Friday, Fridays",
  miércoles: "Wednesday, Wednesdays",
  béisbol: "baseball",
  jueves: "Thursday, Thursdays",
  cumpleaños: "birthday, birthday party, birthdays",
  día: "day",
  qué: "what, how",
  partido: "game, match, departed",
  mañana: "tomorrow, morning, future",
  cuándo: "when",
  martes: "Tuesday, Tuesdays",
  hoy: "today, nowadays",
  lunes: "Monday, Mondays",
  fútbol: "soccer, football",
  uso: "(I) am wearing, (I) am using, (I) use",
  usas: "(?) do you use, (?) are you using, (?) do you wear",
  usa: "(she) is using, (he) is using, (?) does he wear",
  usar: "to use, to wear",
  ayuda: "help, (you-formal) help, (he/she/it) helps",
  necesitas: "(you) need, (?) do you need, need",
  necesita: "(?) does she need, (you) need, (?) does he need",
  quieres: "(?) do you want, (you) want, (you) love",
  quiere: "mean, wants, (?) do you want",
  banana: "banana",
  más: "more, any more, most",
  té: "tea, tea party",
  mal: "unwell, bad, ill",
  ocupada: "busy",
  feliz: "happy, apt, felicitous",
  "te llamas": "your name is, (?) is your name",
  "se llama": "(her) name is, (his) name is, (it) is called",
  ocupado: "busy, been on the game, concerned",
  "cómo está": "how's",
  señor: "Mr., sir, gentleman",
  señorita: "lady, miss, Ms.",
  "buenas tardes": "good afternoon, good evening",
  usted: "you, you'll",
  señora: "ma'am, woman, lady",
  "hasta mañana": "see you tomorrow",
  "hasta luego": "see you later, I'll see you later",
  cansada: "tired, made … tired, tired oneself out",
  bien: "ok, fine, well-to-do",
  cómo: "how's, what, how",
  cansado: "tired, made … tired, tired oneself out",
  estoy: "I'm, am, I am",
  estás: "you are, are, you're",
  mexicano: "Mexican",
  cubano: "Cuban",
  mexicana: "mexican",
  cubana: "Cuban",
  nombre: "name",
  americana: "American",
  España: "Spain",
  "me llamo": "my name is",
  americano: "American",
  medicina: "medicine",
  universidad: "university, college",
  computadora: "computer",
  lees: "read, (you) are reading, (you) read",
  estudias: "(you) study, (?) have you been studyin, (?) do you study",
  escribes: "writing, (you) write, (?) are you writing",
  profesor: "professor",
  escribo: "contribute, (I) write, (I) am writing",
  importante: "important",
  estudio: "(I) am studying, study, (I) study",
  mucho: "a lot",
  comprendo: "understand",
  leo: "I read, read, Leo",
  escribir: "to write",
  pregunta: "question",
  leer: "to read",
  estudiar: "to study",
  problema: "problems, matter, trouble",
  estudiante: "student",
  difícil: "difficult",
  clase: "class",
  fácil: "easy",
  maestro: "teacher",
  examen: "exam",
  libro: "book",
  escuela: "school",
  bolígrafo: "pen",
  demasiado: "too",
  regalo: "gift",
  cinturón: "belt",
  reloj: "watch, clock",
  favorita: "favorite",
  cómoda: "dresser, comfortable, convenient",
  cartera: "purse, bag, wallet",
  diferente: "different",
  abrigo: "coat",
  caro: "expensive",
  ese: "that",
  barato: "cheap",
  falda: "skirt",
  rojo: "red",
  este: "this",
  comprar: "to buy",
  sombrero: "hat",
  gris: "gray, grey",
  camiseta: "T-shirt",
  vestido: "dress",
  marrón: "brown",
  camisa: "shirt, blouse, top",
  ropa: "clothes",
  tienda: "store",
  chaqueta: "jacket",
  azul: "blue",
  verde: "green",
  y: "and",
  hijo: "son",
  interesante: "interesting",
  tienes: "have, are, there's",
  hija: "daughter",
  bicicleta: "bicycle",
  vivo: "alive, brighter, live",
  abuela: "grandmother",
  familia: "family",
  perfecto: "perfect",
  abuelo: "grandfather",
  apartamento: "apartment, flat, condo",
  esposo: "husband",
  esposa: "wife",
  perro: "dog",
  hermano: "brother",
  bonito: "pretty",
  muy: "very",
  gato: "cat",
  hermana: "sister",
  grande: "big",
  casa: "house",
  carro: "car, automobile",
  padre: "father, dad",
  elegante: "elegant",
  tiene: "is, makes, (?) does it have",
  inteligente: "intelligent",
  madre: "mother",
  o: "or",
  pagar: "to pay",
  ensalada: "salad",
  tomate: "tomato",
  quiero: "(I) love, (I) want, want",
  cuenta: "check",
  sal: "salt",
  taza: "cup, mug",
  naranja: "orange",
  café: "coffee",
  vaso: "glass",
  jugo: "juice",
  sin: "absent, without, with no",
  azúcar: "sugar",
  carne: "meat, pork, beef",
  queso: "cheese",
  pescado: "fish",
  de: "with, made of, off",
  con: "with",
  sándwich: "sandwich, sandwiches",
  hamburguesa: "burger, hamburger",
  dos: "two",
  para: "for",
  personas: "people",
  mesa: "table",
  restaurante: "restaurant",
  uno: "one",
  tres: "three",
  supermercado: "supermarket",
  cerrado: "closed",
  banco: "bank, banks",
  calle: "street",
  baño: "bathroom",
  hospital: "hospital, hospitals",
  museo: "museum, museums",
  tu: "your",
  tren: "train",
  autobús: "bus",
  aeropuerto: "airport",
  boleto: "ticket",
  a: "to, with, away",
  dinero: "money",
  dónde: "where",
  reserva: "reservation",
  tengo: "I've got, is there, I'm having",
  está: "it is",
  aquí: "here",
  hotel: "hotel, hotels",
  en: "in",
  maleta: "suitcase",
  pasaporte: "passport",
  mi: "my",
  teléfono: "phone",
  necesito: "need, (I) need, (?) do I need",
  taxi: "taxi, cab",
  español: "Spanish, Spaniard, Spanish man",
  hablo: "(I) am talking, speak, talking",
  hablas: "(?) do you speak, speak, talking",
  disculpe: "excuse me, excuse!, (I/he/she/it/you) excuse",
  inglés: "English, British, Englishman",
  no: "do not, wasn't, n't",
  sí: "yes, yourself",
  "por favor": "please",
  "de nada": "you're welcome, you are welcome",
  perdón: "sorry, excuse me, pardon",
  "lo siento": "sorry, I am sorry",
  adiós: "goodbye",
  "mucho gusto": "nice to meet you, so nice to meet you",
  "buenos días": "good morning",
  gracias: "thanks, thank you, party piece",
  hola: "hello, hi",
  "buenas noches": "good night, good evening",
  bebes: "(?) do you drink, (you) drink, drink",
  agua: "water",
  como: "(I) eat, (I) am eating, like",
  bebo: "(I) drink, (I) am drinking, drink",
  leche: "milk",
  pan: "bread, bar, cake",
  bebe: "(he) is drinking, (you) are drinking, (he) drinks",
  comes: "ate, (you) are eating, (?) do you eat",
  es: "is, are you, it's",
  ella: "she, her, she'll",
  eres: "you're, aren't being, (?) are you",
  él: "he, him, it",
  tú: "you, you'll",
  come: "(it) eats, (?) do you eat, (she) eats",
  manzana: "apple, block",
  soy: "I am, am",
  niño: "boy, child, kid",
  hombre: "man, bloke, guy",
  una: "a, an, one",
  yo: "I, me",
  la: "the, your, her",
  niña: "girl, child, daughter",
  un: "a, an, one",
  el: "the, your, her",
  mujer: "woman, wife, lady",
};
